# Generated by Django 2.1.5 on 2019-02-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
