# Generated by Django 2.1.5 on 2019-02-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190214_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
