# Generated by Django 2.1.5 on 2019-02-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_userprofileinfo_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email_confirmed',
        ),
    ]
